#------------------------------------#
#  Build the SchemaValidator.exe     #
#------------------------------------#
version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - cd Tools
  - nuget restore
build:
  project: Tools/Tools.sln
  verbosity: minimal
artifacts:
- path: Tools\SchemaValidator\bin\$(configuration)
  name: SchemaValidator
  
#------------------------------------#
#    Run the SchemaValidator.exe     #
#------------------------------------#
on_finish:
  - C:\projects\ProductData\Tools\SchemaValidator\bin\Release\SchemaValidator.exe "C:\projects\ProductData\IFC4 Library\IkeaKitchenCabinets.ifcXML"
  - C:\projects\ProductData\Tools\SchemaValidator\bin\Release\SchemaValidator.exe "C:\projects\ProductData\SampleFiles\bSDD product room sample\bSDD product room sample.ifcXML"
  - C:\projects\ProductData\Tools\SchemaValidator\bin\Release\SchemaValidator.exe "C:\projects\ProductData\SampleFiles\CAFM-Connect-ProductsSample\CAFM-Connect-ProductsSample.ifcXML"
  - C:\projects\ProductData\Tools\SchemaValidator\bin\Release\SchemaValidator.exe "C:\projects\ProductData\SampleFiles\CAFM-Connect-ProductsSample\PreClassifiedProduct.ifcXML"
  - C:\projects\ProductData\Tools\SchemaValidator\bin\Release\SchemaValidator.exe "C:\projects\ProductData\SampleFiles\SampleFiles\CatalogExample\catalogExample.ifc"
  - C:\projects\ProductData\Tools\SchemaValidator\bin\Release\SchemaValidator.exe "C:\projects\ProductData\SampleFiles\SampleFiles\CatalogExample\catalogExample.ifcXML"