#------------------------------------#
#  Build the SchemaValidator.exe     #
#------------------------------------#
version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - cd Tools
  - nuget restore
build:
  project: Tools/Tools.sln
  verbosity: minimal
artifacts:
- path: Tools\SchemaValidator\bin\$(configuration)
  name: SchemaValidator
  
#------------------------------------#
#    Run the SchemaValidator.exe     #
#------------------------------------#
on_finish:
  - ps: $ValidatorExe="Tools\SchemaValidator\bin\Release\SchemaValidator.exe"
        $SampleFiles = Get-ChildItem  -Recurse -Include *.ifc,*.ifcXML
        foreach ($file in $SampleFiles | Sort-Object -Property FullName) 
        {
           Write-Host "++++++++++++++++++++++++++++++++++++++"
           Write-Host Validating $file.Name
           Write-Host "++++++++++++++++++++++++++++++++++++++"  
           & $ValidatorExe $file.FullName
        }